services:
  db:
    image: mongo:6.0
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_DEFAULT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_DEFAULT_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-network

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass $REDIS_PASSWORD
    volumes:
      - cache:/data
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
    depends_on:
      - db
      - cache
    ports:
      - 8000:8000
    restart: always
    env_file: .env
    environment:
      - DATABASE_DEFAULT_USERNAME=$DATABASE_DEFAULT_USERNAME
      - DATABASE_DEFAULT_PASSWORD=$DATABASE_DEFAULT_PASSWORD
      - DATABASE_DEFAULT_HOSTNAME=db
      - DATABASE_DEFAULT_PORT=$DATABASE_DEFAULT_PORT
      - DATABASE_DEFAULT_DB=$DATABASE_DEFAULT_DB
      - REDIS_HOSTNAME=cache
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    links:
      - db
      - cache
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  db:
    driver: local
  cache:
    driver: local
